### ISSUE TITLE
Crash on Android during AppIndexing

### ISSUE THREAD

**Issue by kev52** [RodrigoSMarques/flutter_branch_sdk#121]
**Describe the bug**
iOS works fine. But on Android when I call listOnSearch the app crashes with the following logs:  

D/FlutterBranchSDK(22779): listOnSearch call
E/AndroidRuntime(22779): FATAL EXCEPTION: Thread-11
E/AndroidRuntime(22779): Process: com.wanilla.app.dev, PID: 22779
E/AndroidRuntime(22779): java.lang.NoSuchMethodError: No static method getInstance()Lcom/google/firebase/appindexing/FirebaseUserActions; in class Lcom/google/firebase/appindexing/FirebaseUserActions; or its super classes (declaration of 'com.google.firebase.appindexing.FirebaseUserActions' appears in /data/app/~~ykJjhzoXjRYT3mr7Tym55A==/com.wanilla.app.dev-ldABiLtxxAcaaW4kvxxBXA==/base.apk!classes2.dex)
E/AndroidRuntime(22779): 	at io.branch.indexing.AppIndexingHelper$1.run(AppIndexingHelper.java:35)
E/AndroidRuntime(22779): 	at java.lang.Thread.run(Thread.java:923)
D/TransportRuntime.SQLiteEventStore(22779): Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
D/TransportRuntime.JobInfoScheduler(22779): Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=-1853345477 in 1000ms(Backend next call timestamp 1629899534430). Attempt 1
I/BranchSDK(22779): onActivityPaused, activity = com.example.upfit.MainActivity@1da7f1b
I/Process (22779): Sending signal. PID: 22779 SIG: 9
Lost connection to device.

**Comment by RodrigoSMarques** [comment]
Are you using Firebase in your project?

The error message is from Firebase and not Branch.

Run the sample application and the error doesn't happen.
