### ISSUE TITLE
FlutterBranchSdk.initWeb() doesn't work

### ISSUE THREAD

**Issue by stx** [RodrigoSMarques/flutter_branch_sdk#136]
```
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  FlutterBranchSdk.initWeb(branchKey: 'key_live_asdf');
  runApp(const App());
}
```

-> Any SDK call

```
Error: Error: Branch SDK not initialized
    at Object.createErrorWithStack (http://localhost:1234/dart_sdk.js:5076:12)
    at Object._rethrow (http://localhost:1234/dart_sdk.js:40477:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:1234/dart_sdk.js:40473:13)
    at Object._microtaskLoop (http://localhost:1234/dart_sdk.js:40330:13)
    at _startMicrotaskLoop (http://localhost:1234/dart_sdk.js:40336:13)
    at http://localhost:1234/dart_sdk.js:35811:9
```

Script is at top of <body> tag.

**Comment by RodrigoSMarques** [comment]
I'm traveling, with limited computer access.
I will check in the next few days

**Comment by RodrigoSMarques** [comment]
Is the error still occurring?
I couldn't reproduce.
You can run the sample project to verify.

**Comment by stx** [comment]
Yes, still occurs. Only fix for me was https://github.com/RodrigoSMarques/flutter_branch_sdk/issues/114#issuecomment-887307843.
