### ISSUE TITLE
Integration issue with Android

### ISSUE THREAD

**Issue by Rohithgilla12** [RodrigoSMarques/flutter_branch_sdk#151]
Thanks for a great package, but facing an issue with android.

**Describe the bug**
Followed the steps in the documentation and ran the application.

**To Reproduce**
Build the app in android

**Expected behaviour**
Validation passes

The `logcat` output is as follows

```
E/MethodChannel#flutter_branch_sdk/message(28085): Failed to handle method call
E/MethodChannel#flutter_branch_sdk/message(28085): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
E/MethodChannel#flutter_branch_sdk/message(28085): 	at io.branch.referral.validators.BranchIntegrationModel.<init>(BranchIntegrationModel.java:31)
E/MethodChannel#flutter_branch_sdk/message(28085): 	at io.branch.referral.validators.IntegrationValidator.<init>(IntegrationValidator.java:27)
E/MethodChannel#flutter_branch_sdk/message(28085): 	at io.branch.referral.validators.IntegrationValidator.validate(IntegrationValidator.java:32)
E/MethodChannel#flutter_branch_sdk/message(28085): 	at br.com.rsmarques.flutter_branch_sdk.FlutterBranchSdkPlugin.validateSDKIntegration(FlutterBranchSdkPlugin.java:321)
E/MethodChannel#flutter_branch_sdk/message(28085): 	at br.com.rsmarques.flutter_branch_sdk.FlutterBranchSdkPlugin.onMethodCall(FlutterBranchSdkPlugin.java:255)
E/MethodChannel#flutter_branch_sdk/message(28085): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter_branch_sdk/message(28085): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter_branch_sdk/message(28085): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter_branch_sdk/message(28085): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#flutter_branch_sdk/message(28085): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter_branch_sdk/message(28085): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter_branch_sdk/message(28085): 	at android.os.Looper.loop(Looper.java:246)
E/MethodChannel#flutter_branch_sdk/message(28085): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
E/MethodChannel#flutter_branch_sdk/message(28085): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_branch_sdk/message(28085): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/MethodChannel#flutter_branch_sdk/message(28085): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
There was a similar issue a few years back https://github.com/RodrigoSMarques/flutter_branch_sdk/issues/3 that was addressed.

**Desktop (please complete the following information):**
 - Flutter: version: Flutter 2.13.0-0.1.pre • channel beta •
 - Package version: 5.0.0
 - OS: Android

**Smartphone (please complete the following information):**
 - Flutter: version: [e.g. 2.2.3]
 - Package version: [e.g. 3.3.0]

**Additional context**

**Comment by Rohithgilla12** [comment]
I have tried upgrading the android version https://help.branch.io/developers-hub/docs/android-version-history but still no help :(

**Comment by RodrigoSMarques** [comment]
You are having problems with AndroidManifest.xml

Unfortunately, the person responsible for issue #3 did not post his solution.

Post your AndroidMainfest.xml

**Comment by Rohithgilla12** [comment]
Yes, the placement of meta tags were missed.

Also can we update the native sdk to latest if possible many bug fixes are there 😄

**Comment by RodrigoSMarques** [comment]
Yes. There is an improvement in progress and the SDK version will be updated with it.

Can the issue be closed?

**Comment by Rohithgilla12** [comment]
Oh yes definitely
Thanks!

**Comment by quetool** [comment]
I'm on latest `flutter_branch_sdk: ^6.2.1` but Im facing this very same OP's issue. Don't really know what should I do
