### ISSUE TITLE
java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by appeventic** [RodrigoSMarques/flutter_branch_sdk#279]
**Describe the bug**
Getting this error for `FlutterBranchSdk.init` no impact on functionality.

```
D/FlutterBranchSDK(17557): triggered setupBranch
D/FlutterBranchSDK(17557): triggered onNewIntent
D/FlutterBranchSDK(17557): triggered SessionBuilder reInit
W/System.err(17557): java.lang.IllegalStateException: Reply already submitted
W/System.err(17557): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
W/System.err(17557): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:263)
W/System.err(17557): 	at br.com.rsmarques.flutter_branch_sdk.MethodResultWrapper$1.run(MethodResultWrapper.java:25)
W/System.err(17557): 	at android.os.Handler.handleCallback(Handler.java:942)
W/System.err(17557): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(17557): 	at android.os.Looper.loopOnce(Looper.java:240)
W/System.err(17557): 	at android.os.Looper.loop(Looper.java:351)
W/System.err(17557): 	at android.app.ActivityThread.main(ActivityThread.java:8412)
W/System.err(17557): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(17557): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
W/System.err(17557): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
D/FlutterBranchSDK(17557): triggered onInitFinished
D/FlutterBranchSDK(17557): BranchReferralInitListener - params: {"+clicked_branch_link":false,"+is_first_session":false}
```

**To Reproduce**
1. Use 7.0.2 of the package version'
2. In the main.dart use - `await FlutterBranchSdk.init(useTestKey: false, enableLogging: false, disableTracking: true);`
3. Run the app and see the debug console.

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: Flutter version 3.13.1 on channel stable
 - Package version: 7.0.2
 - OS: Android 13
 - Device: OnePlus 8T
 
Only able to repro in Android and this is not consistent.

**Comment by RodrigoSMarques** [comment]
Closed. No activity in the last 15 days.
If necessary open again.
