### ISSUE TITLE
Version 8.0.3 Calling startActivity() from outside of an Activity

### ISSUE THREAD

**Issue by gsouza97** [RodrigoSMarques/flutter_branch_sdk#351]
**Describe the bug**
Hello,

I am facing a bug that I believe is very similar to the one fixed in release **7.0.2**, related to **Calling startActivity() from outside of an Activity.**
I am using version **8.0.3** of the branch_sdk, and the same error continues to occur for some users of my application. The error happens immediately after opening the application, causing the screen to freeze or closing the app.

**Here are the logs:**

package:wade/main.dart line 27 in .setup()
package:flutter_branch_sdk/src/flutter_branch_sdk.dart line 12 in FlutterBranchSdk.init()
PlatformException(error, Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?, null, android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want? at android.app.ContextImpl.startActivity(ContextImpl.java:<NUMBER>) at android.app.ContextImpl.startActivity(ContextImpl.java:<NUMBER>) at android.content.ContextWrapper.startActivity(ContextWrapper.java:442) at k0.b.O(Unknown Source:283) at k0.b.a(Unknown Source:455) at m9.j$a.a(Unknown Source:17) at b9.c.l(Unknown Source:18) at b9.c.m(Unknown Source:41) at b9.c.i(Unknown Source:0) at b9.b.run(Unknown Source:12) at android.os.Handler.handleCallback(Handler.java:942) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:211) at android.os.Looper.loop(Looper.java:300) at android.app.ActivityThread.main(ActivityThread.java:<NUMBER>) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:<NUMBER>) )

**This is how I initialize it in my main.dart:**
<img width="606" alt="image" src="https://github.com/user-attachments/assets/f5b37e88-e524-4da3-8567-18486c556a04">

**To Reproduce**

**Expected behavior**

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: 3.16.5
 - Package version: flutter_branch_sdk: ^8.0.3
 - Device: Redmi 12 (OS: Android 13), Samsung Galaxy A03s (OS: Android 13), Xiaomi Redmi Note 10 (OS: Android 13), Samsung Galaxy A03 (OS: Android 12), Samsung Galaxy A32 (OS: Android 13), Moto E22 (Android 12), Samsung A10 (OS: Android 11).

 
 - **Additional context**

It only happens on Android. On iOS works fine.

**Comment by RodrigoSMarques** [comment]
@gsouza97 

Are you actually using version 8.0.3?

Version 8.x.x no longer uses the `startActivity` method at startup, during the `init` method.

Here is the code in version [7.x.x ](https://github.com/RodrigoSMarques/flutter_branch_sdk/blob/3dbada4a073f31f9012585c8f232c56057423d69/android/src/main/java/br/com/rsmarques/flutter_branch_sdk/FlutterBranchSdkPlugin.java#L458) and here is the code in version [8.x.x](https://github.com/RodrigoSMarques/flutter_branch_sdk/blob/f272fba24e58fc5468f4e3b553fc53be13c7b38e/android/src/main/java/br/com/rsmarques/flutter_branch_sdk/FlutterBranchSdkPlugin.java#L447)

It would not be possible for this to be returned by the plugin.

`handleDeepLink` is the only method that uses startActivity in the code.

**Comment by gsouza97** [comment]
@RodrigoSMarques 
Yes, I am using version 8.0.3.
I also tried using version 7.0.2, but the error persisted.
The main method I use the package for is to handle deeplinkings.
Here is a screenshot of the logs from the build process on Android for both versions I tried:

![image](https://github.com/user-attachments/assets/828d5b8c-0cbf-4d0c-aa25-63b4cc3b1684)

![image](https://github.com/user-attachments/assets/88c72881-158d-4065-8f1c-2dd52c314639)

Both versions result in the same error.

**Comment by RodrigoSMarques** [comment]
> @RodrigoSMarques Yes, I am using version 8.0.3. I also tried using version 7.0.2, but the error persisted. The main method I use the package for is to handle deeplinkings. Here is a screenshot of the logs from the build process on Android for both versions I tried:
> 
> ![image](https://private-user-images.githubusercontent.com/76229106/351504381-828d5b8c-0cbf-4d0c-aa25-63b4cc3b1684.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Mjg4NTcsIm5iZiI6MTcyMTgyODU1NywicGF0aCI6Ii83NjIyOTEwNi8zNTE1MDQzODEtODI4ZDViOGMtMGNiZi00ZDBjLWFhMjUtNjNiNGNjM2IxNjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDEzNDIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkY2YyNTk0YTEwM2MzMTBmNjU4ZjJmNWFiYzhiMmE5MjdlNTkwNzZiZWEyM2QxNDE1YTlmMDFlYWY2YzJiMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YaiVUCwos_JaL98xqxAWmnE2OrLa3iUyB8Ga3jzwx4A)
> 
> ![image](https://private-user-images.githubusercontent.com/76229106/351504599-88c72881-158d-4065-8f1c-2dd52c314639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Mjg4NTcsIm5iZiI6MTcyMTgyODU1NywicGF0aCI6Ii83NjIyOTEwNi8zNTE1MDQ1OTktODhjNzI4ODEtMTU4ZC00MDY1LThmMWMtMmRkNTJjMzE0NjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDEzNDIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzODAyOWUxZGRhNWQ5ZjBjMzczMTc1ZDk0YTM3NTkwNWM5OTUxNWUwOTk1MTFiMGM3MmQ0MDVlZjhhYjFiZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G_4Ls2jm_p1QlMj-xBY5x0EAwbVv76eY4V2FveLQr5E)
> 
> Both versions result in the same error.

Open the Android project subfolder in Android Studio.

Try running the project and see if it opens the line of code where the error is occurring so I can analyze it.

**Comment by RodrigoSMarques** [comment]
Closed. No activity in the last 14 days.
If necessary open again.
