### ISSUE TITLE
[Android] Application crash during launch

### ISSUE THREAD

**Issue by NassB** [RodrigoSMarques/flutter_branch_sdk#95]
Since 1 week, the application I'm working on crashes at each launch with an error related to the flutter_branch_sdk lib without any modification from me and without any update of other lib in the application. So I have to uninstall flutter_branch_sdk and not to use the lib in the application.
I use the lib in version 1.2.0 and I tested with version 1.3.0 but no improvement either.
I tested on Android versions 10, 9 and 7.

Flutter doctor :

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H524 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 4.1)
```

Android 

Here are the logs:

```
2021-03-24 11:29:25.725 15088-15088/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxxxxx.xxxxxx, PID: 15088
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxxxxx.xxxxxx/com.xxxxxx.xxxxxx.MainActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:444)
        at android.content.res.Resources.getString(Resources.java:537)
        at io.branch.referral.BranchUtil.readBranchKey(BranchUtil.java:109)
        at io.branch.referral.Branch.getAutoInstance(Branch.java:456)
        at br.com.rsmarques.flutter_branch_sdk.FlutterBranchSdkInit.init(FlutterBranchSdkInit.java:21)
        at br.com.rsmarques.flutter_branch_sdk.FlutterBranchSdkPlugin.setupChannels(FlutterBranchSdkPlugin.java:99)
        at br.com.rsmarques.flutter_branch_sdk.FlutterBranchSdkPlugin.onAttachedToEngine(FlutterBranchSdkPlugin.java:80)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.add(FlutterEnginePluginRegistry.java:133)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:24)
        at com.xxxxxx.xxxxxx.MainActivity.configureFlutterEngine(MainActivity.kt:10)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:181)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:410)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7660) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

I would like to know if other people have the problem or not.

**Comment by RodrigoSMarques** [comment]
According to the log, the error must be occurring because you are not finding the keys `io.branch.sdk.BranchKey` or `io.branch.sdk.BranchKey.test` in your `AndroidManifest`.

```java
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:444)
        at android.content.res.Resources.getString(Resources.java:537)
        at io.branch.referral.BranchUtil.readBranchKey(BranchUtil.java:109)
```
Needs to be configured:

[https://help.branch.io/developers-hub/docs/android-basic-integration#configure-app](https://help.branch.io/developers-hub/docs/android-basic-integration#configure-app)

**Comment by NassB** [comment]
My bad, that was exactly that, I don't know how and why the application was working without any problem until one week ago and without this information in AndroidManifest.xml. Thank you for your quick response.

**Comment by Nathan187** [comment]
@NassB where did you find the mainactivity.java file and customapplicationclass.java file as well?

**Comment by phvictorino** [comment]
For who is having the same problem, here is my mistake:

![image](https://user-images.githubusercontent.com/8648660/146596191-1ffd98a9-65da-45ec-854c-6b4e16526aad.png)

I inserted the keys into the `<activity>` tag but it needs to be inside the `<application>` and obviously outside `<activity>` tag. 

![image](https://user-images.githubusercontent.com/8648660/146596321-58837fa7-b524-4e61-a8b0-52a2dd4a7d58.png)
